
#设置数据库的地址 解耦合
datasource:
  url: localhost:3306/zhineng

spring:
  datasource: # spring下  数据库配置
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${datasource.url}?useSSL=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&autoReconnect=true&failOverReadOnly=false&maxReconnects=10&serverTimezone=UTC
    username: root
    password: root
    hikari:
      maximum-pool-size: 10 # 最大连接池数
      max-lifetime: 1770000

  thymeleaf:
    cache: false #关闭缓存

  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB


#  swagger启动报错
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher




#mybatis 配置  和spring 的datasource 配合
mybatis:
  # 指定别名设置的包为所有entity
  type-aliases-package: com.ncyteng.zhineng.pojo
  configuration:
    map-underscore-to-camel-case: true # 驼峰命名规范
  #    map-underscore-to-camel-case: true ， 用来开启驼峰命名规范，这个比较好用，比
  #如数据库中字段名为： user_name ， 那么在实体类中可以定义属性为 userName （甚至可以写成
  #username ，也能映射上），会自动匹配到驼峰属性，如果不这样配置的话，针对字段名和属性名不同
  #的情况，会映射不到。
  mapper-locations: # mapper映射文件位置
    - classpath:mapper/*.xml

jwt:
  secret: sfadsklfhafansdkfjshdfsdkfhal
  expire: 3600
  header: token
#   header 接收的变量
#  expire 设置jwt过期时间 单位是秒
#  secret设置密钥，随便写

#设置照片地址
uploadPath: D:\\java\\project\\zhineng\\image


#编辑器配置
ue:
  config-file: static/ueditor-1.4.3.3/jsp/config.json #resources目录下配置文件的位置
  server-url: /ueditor.do #服务器统一请求接口路径
  local: #上传到本地配置
    url-prefix: /file/ #"/"结尾 自定义上传时字段无意义
    physical-path: D:/java/project/zhineng/image #ueditor存储文件的绝对路径 必须使用标准路径"/"作为分隔符  自定义上传时字段无意义
